
// Generated by FABulous
// Top wrapper for user design /home/jart/work/uni/FABulous/demo_ACF/demo_4x4/user_design/sequential_16bit_en.v

module top_wrapper;

wire clk;
(* keep *) Global_Clock clk_i (.CLK(clk));

(* keep, BEL="X0Y4.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y4_B (.I(IO_1_bidirectional_frame_config_pass_I[0]), .T(IO_1_bidirectional_frame_config_pass_T[0]), .O(IO_1_bidirectional_frame_config_pass_O[0]), .Q(IO_1_bidirectional_frame_config_pass_Q[0]));
(* keep, BEL="X0Y4.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y4_A (.I(IO_1_bidirectional_frame_config_pass_I[1]), .T(IO_1_bidirectional_frame_config_pass_T[1]), .O(IO_1_bidirectional_frame_config_pass_O[1]), .Q(IO_1_bidirectional_frame_config_pass_Q[1]));
(* keep, BEL="X0Y3.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y3_B (.I(IO_1_bidirectional_frame_config_pass_I[2]), .T(IO_1_bidirectional_frame_config_pass_T[2]), .O(IO_1_bidirectional_frame_config_pass_O[2]), .Q(IO_1_bidirectional_frame_config_pass_Q[2]));
(* keep, BEL="X0Y3.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y3_A (.I(IO_1_bidirectional_frame_config_pass_I[3]), .T(IO_1_bidirectional_frame_config_pass_T[3]), .O(IO_1_bidirectional_frame_config_pass_O[3]), .Q(IO_1_bidirectional_frame_config_pass_Q[3]));
(* keep, BEL="X0Y2.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y2_B (.I(IO_1_bidirectional_frame_config_pass_I[4]), .T(IO_1_bidirectional_frame_config_pass_T[4]), .O(IO_1_bidirectional_frame_config_pass_O[4]), .Q(IO_1_bidirectional_frame_config_pass_Q[4]));
(* keep, BEL="X0Y2.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y2_A (.I(IO_1_bidirectional_frame_config_pass_I[5]), .T(IO_1_bidirectional_frame_config_pass_T[5]), .O(IO_1_bidirectional_frame_config_pass_O[5]), .Q(IO_1_bidirectional_frame_config_pass_Q[5]));
(* keep, BEL="X0Y1.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y1_B (.I(IO_1_bidirectional_frame_config_pass_I[6]), .T(IO_1_bidirectional_frame_config_pass_T[6]), .O(IO_1_bidirectional_frame_config_pass_O[6]), .Q(IO_1_bidirectional_frame_config_pass_Q[6]));
(* keep, BEL="X0Y1.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y1_A (.I(IO_1_bidirectional_frame_config_pass_I[7]), .T(IO_1_bidirectional_frame_config_pass_T[7]), .O(IO_1_bidirectional_frame_config_pass_O[7]), .Q(IO_1_bidirectional_frame_config_pass_Q[7]));


// bel IO_1_bidirectional_frame_config_pass input wires:
wire [7:0]IO_1_bidirectional_frame_config_pass_I;
wire [7:0]IO_1_bidirectional_frame_config_pass_T;
// bel IO_1_bidirectional_frame_config_pass output wires:
wire [7:0]IO_1_bidirectional_frame_config_pass_O;
wire [7:0]IO_1_bidirectional_frame_config_pass_Q;


// instantiate user_design
sequential_16bit_en user_design_i (.clk(clk), .io_in(IO_1_bidirectional_frame_config_pass_O), .io_out(IO_1_bidirectional_frame_config_pass_I), .io_oeb(IO_1_bidirectional_frame_config_pass_T));


endmodule //top_wrapper
